# Generated by Django 3.2.18 on 2023-04-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
